version: '3.4'

services:
  taskmanagementsystem:
    image: taskmanagementsystem:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./data:/app/data
